### PR TITLE
Add geometry.nim

### PR DESCRIPTION
**Pull request by JacopoFera**
This PR adds new geometry features to traynim

### CODE REVIEW

**Comment by ottyanna** [comment]
Hi @JacopoFera, I changed your definitions of `DefineDotProd` and `DefineScalarProd` templates at line 89 and 96. I think a better way to define these two operations is to make an overload of the `*` operator. Let me know what you think. Cheers :)

**Comment by ottyanna** [comment]
**TO DO:**

For `Vec`, `Point` and `Normal` types:
- [x] New3d object Procedure
  - [x] Test 
- [x] Stringify Expression for `Vec`, `Point` and `Normal` types
  - [x] Test
- [x] Sum/diff for `Vec` and `Point` types
  - [x] Test
- [x] Scalar * Vector Product for `Vec` and `Normal` types
  - [x] Test
- [x] Scalar Product for `Vec` and `Normal` types
  - [x] Test
- [x] Vector Product for `Vec` and `Normal` types
  - [x] Test
- [x] areClose procedure for `Vec`, `Point` and `Normal` types
  - [x]  Test
- [x] Normal and SquaredNormal procedures for `Vec` and `Normal` types
  - [x] Test 
- [x] `ParseVecNormal` for `Vec` type and `ParsePointVec` to `Point` type
  - [x] Test

For Transformation type:
- [x] New Transformation Procedure
- [x] standard Tranformations, i.e. Translations, Rotations and Scaling
  - [x] Test
- [x] isConsistent procedure
  - [x] Test
- [x] Inverse tranformation 
  - [x] Test     
- [x] Products
  - [x] Test

**Comment by JacopoFera** [comment]
Hey @ottyanna, I've just added the norm/sqrNorm proc in the file plus the tests. I also implemented a basic newTrasformation proc and a basic matrix multiplication proc to test if everything ran smoothly out of the box. Check it out and let me know :)

**Comment by ottyanna** [comment]
Hi @JacopoFera, thank you! I actually separated the transformations from the other geometry elements, hope this is a good idea. Then I added some of the procedures and tests. Finally I changed the folder system as we said last time (this meant I had to change also the .gitignore file). Let me know if everything is ok!
I almost forgot, we can actually think of using the `block` feature to separate the parts in the test file. Let me know if this sounds good to you :)

**Pull request merged**
